# Settings
- defaults:
    link:
      create: true
      relink: true
      # force: true # Swap the original file

# TODO: ?
- clean: ['~', '~/.config']

# Run shell commands
- shell:
  - [git submodule update --init --recursive, Installing submodules]

# TODO: add shell command to cd to antibody and download zsh plugins. Maybe need to install Antibody too (ask user).
# TODO: install Nix
# TODO: install all the commands I use with Nix

# TODO: look into https://github.com/LnL7/nix-darwin and maybe add/use it
# TODO: look into https://github.com/rycee/home-manager and maybe add/use it

# Symlink files
- link:
    # Zsh
    ~/.zshrc: zsh/zshrc.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # Hammerspoon
    ~/.hammerspoon: hammerspoon
    # Karabiner
    "~/Library/Application Support/Karabiner": karabiner
    # Sublime Text
    "~/Library/Application Support/Sublime Text 3/Packages/User": sublime
    # Neovim
    ~/.config/nvim: nvim
    # Bash
    ~/.bashrc: bash/bashrc
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json

# macOS Time Machine install:
# 1. Boot into new macOS with hard drive that has Time Machine backup inside.
# 1. Boot macOS from time machine.

# macOS fresh install:
# NOTE: Use Disk Utility in recovery partition to erase the hard drive to replace system files for full reset.
# 1. Go to recovery partition. Reinstall macOS from scratch, don’t select the option to reinstall from Time Machine.
# 1. Go through install process, setup a new account, then log in.
# 2. When logged in, open Time Machine Migration Assistant and chose what you want to transfer from it.
# 2. You can select specific things like Applications, Documents, etc.

# `~/Library/Application Support/` -> where apps store auxiliary files.
# `~/Library/Preferences/` -> where apps store preferences.

# 3. Clone dotfiles and run ./install.
