language: ruby
os:
  - linux
  - osx
install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh
  else
    brew update >/dev/null
    brew install shellcheck shfmt zsh
  fi
script:
  - curl -sL https://git.io/shcheck | bash -x -s 
  - ./script/test
notifications:
  email: false 
